CodeLinkMVC/CodeLinkMVC/Controllers/QuestionAskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CodeLinkMVC.Models;

namespace CodeLinkMVC.Controllers
{
    public class QuestionAskController : Controller
    {
        private readonly SurveyContext _context;

        public QuestionAskController(SurveyContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> GetNextQ()
        {
            //Hardcode in UID
            //int UID = 1;
            var next = 0;
            var check = _context.SurveyAnswer
                            .Where(s => s.Answer != null);
            if (check.Any())
            {

                var answer = _context.SurveyAnswer
                                    // .Where(s => s.UID = UID)
                                    .Join(_context.SurveyQuestion,
                                    c => c.QID,
                                    s => s.Id,
                                    (c, s) => new
                                    {
                                        Answer = c.Answer,
                                        QID = c.QID,
                                        Order = s.Seq
                                    }
                                    )
                                    .Where(s => s.Answer != null)
                                    .OrderByDescending(s => s.Order)
                                    .First();


                next = answer.Order;
                next++;
            }

            var nextQ = _context.SurveyQuestion
                            .Where(s => s.Seq == next)
                            .FirstOrDefault();
            if (nextQ == null)
            {
                return RedirectToAction("Dashboard","Home", new { area = "" });
            }
            var viewModel = new QAnswerViewModel();
            viewModel.Question = nextQ;
            viewModel.Answer = new SurveyAnswerModel();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Answer( QAnswerViewModel result)
        {
            if (ModelState.IsValid)
            {
                result.Answer.Id = Guid.NewGuid();
                result.Answer.QID = result.Question.Id;

                _context.Add(result.Answer);
                _context.SaveChangesAsync();
                return RedirectToAction(nameof(GetNextQ));
            }
            return Ok();
        }
    }
}

CodeLinkMVC/CodeLinkMVC/Controllers/SurveyAnswerModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CodeLinkMVC.Models;

namespace CodeLinkMVC.Controllers
{
    public class SurveyAnswerModelsController : Controller
    {
        private readonly SurveyContext _context;

        public SurveyAnswerModelsController(SurveyContext context)
        {
            _context = context;
        }

        // GET: SurveyAnswerModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.SurveyAnswer.ToListAsync());
        }

        // GET: SurveyAnswerModels/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var surveyAnswerModel = await _context.SurveyAnswer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (surveyAnswerModel == null)
            {
                return NotFound();
            }

            return View(surveyAnswerModel);
        }

        // GET: SurveyAnswerModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SurveyAnswerModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UID,QID,Answer")] SurveyAnswerModel surveyAnswerModel)
        {
            if (ModelState.IsValid)
            {
                surveyAnswerModel.Id = Guid.NewGuid();
                _context.Add(surveyAnswerModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(surveyAnswerModel);
        }

        // GET: SurveyAnswerModels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var surveyAnswerModel = await _context.SurveyAnswer.FindAsync(id);
            if (surveyAnswerModel == null)
            {
                return NotFound();
            }
            return View(surveyAnswerModel);
        }

        // POST: SurveyAnswerModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,UID,QID,Answer")] SurveyAnswerModel surveyAnswerModel)
        {
            if (id != surveyAnswerModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(surveyAnswerModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SurveyAnswerModelExists(surveyAnswerModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(surveyAnswerModel);
        }

        // GET: SurveyAnswerModels/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var surveyAnswerModel = await _context.SurveyAnswer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (surveyAnswerModel == null)
            {
                return NotFound();
            }

            return View(surveyAnswerModel);
        }

        // POST: SurveyAnswerModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var surveyAnswerModel = await _context.SurveyAnswer.FindAsync(id);
            _context.SurveyAnswer.Remove(surveyAnswerModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SurveyAnswerModelExists(Guid id)
        {
            return _context.SurveyAnswer.Any(e => e.Id == id);
        }
    }
}

CodeLinkMVC/CodeLinkMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeLinkMVC</title>
   
    <link rel="stylesheet" href="/bootstrap-4.3.1-dist/css/bootstrap.min.css">



    <link href="/css/carousel.css" rel="stylesheet">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <img src="/media/servantNavBarLogo.png" class="rounded" alt="" width="40" height="40">
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Dashboard">Dashboard</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="#">VET ++</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="LogOut">Log Out</a>
                </li>
            </ul>
        </div>
    </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <footer class="container" style="padding-top: 2rem">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; Developing Developers &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        <p><a class="nav-link text-dark" asp-area="" asp-controller="SurveyQuestion" asp-action="Index">Quest</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="QuestionAsk" asp-action="GetNextQ">Ans</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="SurveyAnswerModels" asp-action="Index">Admin</a></p>
    </footer>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="/bootstrap-4.3.1-dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

@RenderSection("Scripts", required: false)
</body>
</html>